export const USER_DATA = 'USER_DATA';
export const SET_USER_TYPE = 'SET_USER_TYPE';

export const NOTICE_LIST_REQUEST = 'NOTICE_LIST_REQUEST';
export const NOTICE_LIST_SUCCESS = 'NOTICE_LIST_SUCCESS';
export const NOTICE_LIST_FAIL = 'NOTICE_LIST_FAIL';
export const NOTICE_LIST_REQUEST_SILENT = 'NOTICE_LIST_REQUEST_SILENT';

export const NOTICE_DELETE_REQUEST = 'NOTICE_DELETE_REQUEST';
export const NOTICE_DELETE_SUCCESS = 'NOTICE_DELETE_SUCCESS';
export const NOTICE_DELETE_FAIL = 'NOTICE_DELETE_FAIL';

export const COMPLAINT_LIST_REQUEST = 'COMPLAINT_LIST_REQUEST';
export const COMPLAINT_LIST_SUCCESS = 'COMPLAINT_LIST_SUCCESS';
export const COMPLAINT_LIST_FAIL = 'COMPLAINT_LIST_FAIL';

export const SOCIETY_DETAIL_REQUEST = 'SOCIETY_DETAIL_REQUEST';
export const SOCIETY_DETAIL_SUCCESS = 'SOCIETY_DETAIL_SUCCESS';
export const SOCIETY_DETAIL_FAIL = 'SOCIETY_DETAIL_FAIL';

export const GET_MAINTANCE_USER_REQUEST = 'GET_MAINTANCE_USER_REQUEST';
export const GET_MAINTANCE_USER_SUCCESS = 'GET_MAINTANCE_USER_SUCCESS';
export const GET_MAINTANCE_USER_FAIL = 'GET_MAINTANCE_USER_FAIL';

export const PAYMENT_DETAIL_REQUEST = 'PAYMENT_DETAIL_REQUEST';
export const PAYMENT_DETAIL_FAIL = 'PAYMENT_DETAIL_FAIL';
export const PAYMENT_DETAIL_SUCCESS = 'PAYMENT_DETAIL_SUCCESS';

export const PRE_PAYMENT_DETAIL_REQUEST = 'PRE_PAYMENT_DETAIL_REQUEST';
export const PRE_PAYMENT_DETAIL_SUCCESS = 'PRE_PAYMENT_DETAIL_SUCCESS';
export const PRE_PAYMENT_DETAIL_FAIL = 'PRE_PAYMENT_DETAIL_FAIL';

export const LOGIN_OPTION = 'LOGIN_OPTION';

export const GET_VISITORS_LIST_REQUEST = 'GET_VISITORS_LIST_REQUEST';
export const GET_VISITORS_LIST_FAIL = 'GET_VISITORS_LIST_FAIL';
export const GET_VISITORS_LIST_SUCCESS = 'GET_VISITORS_LISUCCESSEST';

export const UPDATE_VISITORS_LIST = 'UPDATE_VISITORS_LIST';

export const GET_RESIDENTSLIST_REQUEST = 'GET_RESIDENTSLIST_REQUEST';
export const GET_RESIDENTSLIST_SUCCESS = 'GET_RESIDENTSLIST_SUCCESS';
export const GET_RESIDENTSLIST_FAIL = 'GET_RESIDENTSLIST_FAIL';

export const EDIT_RESIDENT_USER_REQUEST = 'EDIT_RESIDENT_USER_REQUEST';
export const EDIT_RESIDENT_USER_SUCCESS = 'EDIT_RESIDENT_USER_SUCCESS';
export const EDIT_RESIDENT_USER_FAIL = 'EDIT_RESIDENT_USER_FAIL';

export const GET_CONTACT_PROFESSION_REQUEST = 'GET_CONTACT_PROFESSION_REQUEST';
export const GET_CONTACT_PROFESSION_SUCCESS = 'GET_CONTACT_PROFESSION_SUCCESS';
export const GET_CONTACT_PROFESSION_FAIL = 'GET_CONTACT_PROFESSION_FAIL';
