export const USER_DATA = 'USER_DATA';
export const SET_USER_TYPE = 'SET_USER_TYPE';

export const NOTICE_LIST_REQUEST = 'NOTICE_LIST_REQUEST';
export const NOTICE_LIST_SUCCESS = 'NOTICE_LIST_SUCCESS';
export const NOTICE_LIST_FAIL = 'NOTICE_LIST_FAIL';

export const COMPLAINT_LIST_REQUEST = 'COMPLAINT_LIST_REQUEST';
export const COMPLAINT_LIST_SUCCESS = 'COMPLAINT_LIST_SUCCESS';
export const COMPLAINT_LIST_FAIL = 'COMPLAINT_LIST_FAIL';

export const SOCIETY_DETAIL_REQUEST = 'SOCIETY_DETAIL_REQUEST';
export const SOCIETY_DETAIL_SUCCESS = 'SOCIETY_DETAIL_SUCCESS';
export const SOCIETY_DETAIL_FAIL = 'SOCIETY_DETAIL_FAIL';

export const GET_MAINTANCE_USER_REQUEST = 'GET_MAINTANCE_USER_REQUEST';
export const GET_MAINTANCE_USER_SUCCESS = 'GET_MAINTANCE_USER_SUCCESS';
export const GET_MAINTANCE_USER_FAIL = 'GET_MAINTANCE_USER_FAIL';

export const PAYMENT_DETAIL_REQUEST = 'PAYMENT_DETAIL_REQUEST';
export const PAYMENT_DETAIL_FAIL = 'PAYMENT_DETAIL_FAIL';
export const PAYMENT_DETAIL_SUCCESS = 'PAYMENT_DETAIL_SUCCESS';

export const PRE_PAYMENT_DETAIL_REQUEST = 'PRE_PAYMENT_DETAIL_REQUEST';
export const PRE_PAYMENT_DETAIL_SUCCESS = 'PRE_PAYMENT_DETAIL_SUCCESS';
export const PRE_PAYMENT_DETAIL_FAIL = 'PRE_PAYMENT_DETAIL_FAIL';

export const LOGIN_OPTION = 'LOGIN_OPTION';
